- name: Add NodeSource GPG key
  # wget -qO- https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  tags:
    - root
    - vim_coc_nvim
- name: Add NodeSource apt repository for Node.js 18.x
  # sudo add-apt-repository "deb https://deb.nodesource.com/node_18.x focal main" -y
  apt_repository:
    repo: deb https://deb.nodesource.com/node_18.x focal main
    state: present
    update_cache: yes
  tags:
    - root
    - vim_coc_nvim
- name: Install Node.js and npm
  # sudo apt-get install -y nodejs
  apt:
    name: nodejs
    state: present
  tags:
    - root
    - vim_coc_nvim

- name: Check Yarn
  command: "which yarn"
  register: yarn_check
  ignore_errors: true

- name: Install Yarn globally
  # npm install -g yarn
  npm:
    name: yarn
    state: present
    global: yes
  when: yarn_check.rc != 0
  tags:
    - root
    - vim_coc_nvim
