- name: Install global required packages
  # sudo apt-get install -y vim gcc libncurses-dev make exuberant-ctags
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - gcc
    - libncurses-dev
    - make
    - exuberant-ctags
  tags:
    - root
    - vim_global
