- name: Update APT package index
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Download Docker GPG key
  get_url:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    dest: "/tmp/docker-gpg-key"

- name: Add Docker GPG key
  command: "sudo apt-key add /tmp/docker-gpg-key"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Update APT package index again
  apt:
    update_cache: yes

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Pull v2ray/official image
  command: "docker pull v2ray/official"

- name: Create docker group
  group:
    name: docker
    state: present

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker
