name: Docker Image Version Tracker (linux/amd64 only)

on:
  workflow_dispatch: # 手动触发

jobs:
  check-latest-version-and-save:
    runs-on: ubuntu-latest

    steps:
    # 设置 Docker 默认架构为 linux/amd64
    - name: Set platform to linux/amd64
      run: |
        export DOCKER_CLI_PLATFORM=linux/amd64

    # 拉取 v2fly/v2fly-core 最新镜像
    - name: Pull latest v2fly/v2fly-core
      run: |
        docker pull --platform linux/amd64 v2fly/v2fly-core:latest

    # 获取并保存最新版本号
    - name: Record latest version and save image
      run: |
        IMAGE_ID=$(docker images --format "{{.ID}}" v2fly/v2fly-core:latest | head -n 1)
        VERSION=$(docker inspect $IMAGE_ID | jq -r '.[0].RepoTags[0]' | sed 's/:/-/g')  # 替换冒号为短横线
        echo "Latest Version: $VERSION"
        
        # 保存镜像为 tar 文件，使用版本号作为文件名
        docker save -o "v2fly-core-${VERSION}-linux-amd64.tar" v2fly/v2fly-core:latest

    # 上传版本信息和镜像文件
    - name: Upload version info and Docker image
      uses: actions/upload-artifact@v3
      with:
        name: v2fly-core-latest
        path: |
          v2fly-core-latest-version.txt
          v2fly-core-${VERSION}-linux-amd64.tar
