name: Docker Image Downloader (linux/amd64 only)

on:
  workflow_dispatch: # 手动触发

jobs:
  download-and-save:
    runs-on: ubuntu-latest

    steps:
    # 设置 Docker 默认架构为 linux/amd64
    - name: Set platform to linux/amd64
      run: |
        export DOCKER_CLI_PLATFORM=linux/amd64

    # 拉取 v2fly/v2fly-core 最新镜像
    - name: Pull latest v2fly/v2fly-core
      run: |
        docker pull --platform linux/amd64 v2fly/v2fly-core:latest

    # 保存镜像为 tar 文件，文件名为固定名称
    - name: Save Docker image to file
      run: |
        docker save -o "v2fly-core-latest-linux-amd64.tar" v2fly/v2fly-core:latest

    # 上传镜像文件
    - name: Upload Docker image
      uses: actions/upload-artifact@v3
      with:
        name: v2fly-core-latest
        path: v2fly-core-latest-linux-amd64.tar
